apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: production
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      # 🔐 ADD THIS BLOCK BELOW
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-rds-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-db-secret
  namespace: production
spec:
  refreshInterval: 1h # Automatically update secrets if rotated in AWS Secrets Manager
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: app-db-credentials # Name of the K8s Secret created dynamically by ESO
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: production/rds/credentials # Path key name inside AWS Secrets Manager
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: production/rds/credentials
        property: password