apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-backend     # 🔍 1. The selector looks for this label
  template:
    metadata:
      # 🛠️ FIX: ADD THESE TWO LINES BACK IN PERFECTLY ALIGNED
      labels:
        app: retail-backend   # 🎯 2. MUST match the selector exactly!
    spec:
      containers:
      - name: api
        image: 154290454465.dkr.ecr.ap-south-1.amazonaws.com/retail-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "production-postgres-db.c3u4eyeaiq53.ap-south-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "retail_prod"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: DB_PASSWORD
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: retail-backend-service
  namespace: production
spec:
  type: ClusterIP # Kept private inside the cluster network bounds
  selector:
    app: retail-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
